# Generated by Django 5.1.1 on 2024-09-28 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrerItem",
            new_name="OrderItem",
        ),
    ]
